---
language: minimal

before_install:
  - 'curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"'
  - 'unzip awscli-bundle.zip'
  - './awscli-bundle/install -b ~/bin/aws'
  - 'export PATH=~/bin:$PATH'

addons:
  apt:
    packages:
    - sshpass

matrix:
  include:
    - stage: Test
      language: go
      go: "1.14.x"
      script: make unit-test
    - stage: Test
      language: go
      go: "1.14.x"
      script: make e2e-test